spring.application.name=EurekaServer
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.file.name=C:/log/EurekaServer.log
logging.level.org.springframework.cloud.gateway=DEBUG
